export const PLANNING_FETCH = 'PLANNING_FETCH';
export const PLANNING_LOADING = 'PLANNING_LOADING';
export const PLANNING_ADD = 'PLANNING_ADD';
export const PLANNING_FETCH_ERROR = 'PLANNING_FETCH_ERROR';
export const FILTER_SET = 'FILTER_SET';
